/**
 * WeldScan 3D — Node.js PDF Blueprint Generator
 *
 * Uses PDFKit to produce a printable blueprint from analysis results.
 * Returns a Promise<Buffer> containing the PDF bytes.
 */

const PDFDocument = require('pdfkit');

const MARGIN = 72; // 1 inch margins
const PAGE_W = 612;
const PAGE_H = 792;

/**
 * Generate a blueprint PDF.
 *
 * @param {Array}  cutList      - [{label, lengthIn, lengthMm, miterDeg, kerfAdjLengthMm}]
 * @param {Object} summary      - {bboxWidthIn, bboxWidthMm, bboxHeightIn, bboxHeightMm, totalLengthMm, totalPieces}
 * @param {Object} welderCalcs  - {bendDeductionMm, rootGapMm, landingMm, weldVolumeCm3, weldVolumeIn3}
 * @param {string} [title]
 * @returns {Promise<Buffer>}
 */
function generatePdfBlueprint(cutList, summary, welderCalcs, title = 'WeldScan 3D Blueprint') {
  return new Promise((resolve, reject) => {
    const chunks = [];
    const doc = new PDFDocument({ size: 'LETTER', margin: MARGIN });

    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // ── Title ────────────────────────────────────────────────────────────────
    doc
      .fontSize(18)
      .font('Helvetica-Bold')
      .text(title, { align: 'center' });

    doc.moveDown(0.4);

    // ── Divider ──────────────────────────────────────────────────────────────
    doc
      .moveTo(MARGIN, doc.y)
      .lineTo(PAGE_W - MARGIN, doc.y)
      .strokeColor('#FF6B00')
      .lineWidth(1.5)
      .stroke()
      .strokeColor('black')
      .lineWidth(1);

    doc.moveDown(0.5);

    // ── Summary box ───────────────────────────────────────────────────────────
    doc.fontSize(10).font('Helvetica');
    const fmt = (v, dp = 2) => (v != null ? Number(v).toFixed(dp) : 'N/A');

    doc.text(`Overall Width:   ${fmt(summary.bboxWidthIn, 3)}"  (${fmt(summary.bboxWidthMm, 1)} mm)`);
    doc.text(`Overall Height:  ${fmt(summary.bboxHeightIn, 3)}"  (${fmt(summary.bboxHeightMm, 1)} mm)`);
    doc.text(`Total Cut Length: ${fmt(summary.totalLengthMm, 1)} mm`);
    doc.text(`Total Pieces:     ${summary.totalPieces ?? cutList.length}`);

    doc.moveDown(0.8);

    // ── Cut-list table ────────────────────────────────────────────────────────
    const cols = {
      piece:    MARGIN,
      lengthIn: MARGIN + 56,
      lengthMm: MARGIN + 140,
      miter:    MARGIN + 230,
      kerfAdj:  MARGIN + 316,
    };

    doc.fontSize(10).font('Helvetica-Bold').text('Cut List', { underline: true });
    doc.moveDown(0.3);

    const hY = doc.y;
    doc.fontSize(9).font('Helvetica-Bold');
    doc.text('Piece',        cols.piece,    hY, { lineBreak: false });
    doc.text('Length (in)',  cols.lengthIn,  hY, { lineBreak: false });
    doc.text('Length (mm)',  cols.lengthMm,  hY, { lineBreak: false });
    doc.text('Miter°',       cols.miter,     hY, { lineBreak: false });
    doc.text('Kerf-Adj mm',  cols.kerfAdj,   hY);

    let y = doc.y + 2;
    doc.moveTo(MARGIN, y).lineTo(PAGE_W - MARGIN, y).stroke();
    y += 4;

    doc.fontSize(9).font('Helvetica');
    for (const chunk of cutList) {
      if (y > PAGE_H - MARGIN - 80) {
        doc.addPage();
        y = MARGIN;
      }
      doc.text(chunk.label,                       cols.piece,    y, { lineBreak: false });
      doc.text(Number(chunk.lengthIn).toFixed(3),  cols.lengthIn,  y, { lineBreak: false });
      doc.text(Number(chunk.lengthMm).toFixed(2),  cols.lengthMm,  y, { lineBreak: false });
      doc.text(Number(chunk.miterDeg).toFixed(1),  cols.miter,     y, { lineBreak: false });
      doc.text(Number(chunk.kerfAdjLengthMm).toFixed(2), cols.kerfAdj, y);
      y += 14;
    }

    y += 14;

    // ── Welder calculations ───────────────────────────────────────────────────
    if (y > PAGE_H - MARGIN - 80) { doc.addPage(); y = MARGIN; }

    doc.fontSize(10).font('Helvetica-Bold').text('Welder Calculations', MARGIN, y, { underline: true });
    y += 18;
    doc.fontSize(9).font('Helvetica');
    doc.text(`Bend Deduction: ${fmt(welderCalcs.bendDeductionMm, 3)} mm`, MARGIN, y); y += 14;
    doc.text(`Root Gap: ${fmt(welderCalcs.rootGapMm, 2)} mm  |  Landing: ${fmt(welderCalcs.landingMm, 2)} mm`, MARGIN, y); y += 14;
    doc.text(`Weld Volume: ${fmt(welderCalcs.weldVolumeCm3, 4)} cm³  (${fmt(welderCalcs.weldVolumeIn3, 4)} in³)`, MARGIN, y);

    // ── Footer ────────────────────────────────────────────────────────────────
    doc
      .fontSize(8)
      .font('Helvetica-Oblique')
      .text('Generated by WeldScan 3D — metalcut.pro', MARGIN, PAGE_H - 36, { align: 'center' });

    doc.end();
  });
}

module.exports = { generatePdfBlueprint };
