"""
WeldScan 3D — Export Module

Generates blueprint PDFs and CNC-ready DXF files from the cut list.

Dependencies:
    pip install reportlab ezdxf
"""

import io
import math
from typing import Optional

# reportlab — PDF generation
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas as rl_canvas

# ezdxf — DXF generation
import ezdxf
from ezdxf.enums import TextEntityAlignment


# ---------------------------------------------------------------------------
# PDF Blueprint
# ---------------------------------------------------------------------------

def generate_pdf_blueprint(
    cut_list: list[dict],
    summary: dict,
    welder_calcs: dict,
    title: str = "WeldScan 3D Blueprint",
) -> bytes:
    """
    Generate an annotated blueprint PDF.

    Args:
        cut_list:     list of chunk dicts from chunk_generator.generate_cut_list
        summary:      bounding-box and total-length dict
        welder_calcs: bend deduction, root gap, weld volume dict
        title:        project title string

    Returns:
        PDF file content as bytes
    """
    buf = io.BytesIO()
    c = rl_canvas.Canvas(buf, pagesize=letter)
    width, height = letter

    # Title
    c.setFont("Helvetica-Bold", 18)
    c.drawCentredString(width / 2, height - 1 * inch, title)

    # Summary box
    c.setFont("Helvetica", 10)
    y = height - 1.6 * inch
    c.drawString(1 * inch, y, f"Overall Width: {summary.get('bboxWidthIn', 0):.3f}\"  "
                               f"({summary.get('bboxWidthMm', 0):.1f} mm)")
    y -= 14
    c.drawString(1 * inch, y, f"Overall Height: {summary.get('bboxHeightIn', 0):.3f}\"  "
                               f"({summary.get('bboxHeightMm', 0):.1f} mm)")
    y -= 14
    c.drawString(1 * inch, y, f"Total Cut Length: {summary.get('totalLengthMm', 0):.1f} mm")

    # Cut-list table header
    y -= 30
    c.setFont("Helvetica-Bold", 10)
    c.drawString(1 * inch, y, "Piece")
    c.drawString(2 * inch, y, "Length (in)")
    c.drawString(3.5 * inch, y, "Length (mm)")
    c.drawString(5 * inch, y, "Miter Angle°")
    c.drawString(6.5 * inch, y, "Kerf-Adj (mm)")
    y -= 4
    c.line(1 * inch, y, width - 1 * inch, y)
    y -= 14

    c.setFont("Helvetica", 9)
    for chunk in cut_list:
        if y < 1.5 * inch:
            c.showPage()
            y = height - 1 * inch
            c.setFont("Helvetica", 9)
        c.drawString(1 * inch, y, chunk["label"])
        c.drawString(2 * inch, y, f"{chunk['lengthIn']:.3f}")
        c.drawString(3.5 * inch, y, f"{chunk['lengthMm']:.2f}")
        c.drawString(5 * inch, y, f"{chunk['miterDeg']:.1f}")
        c.drawString(6.5 * inch, y, f"{chunk['kerfAdjLengthMm']:.2f}")
        y -= 14

    # Welder calculations section
    y -= 20
    c.setFont("Helvetica-Bold", 10)
    c.drawString(1 * inch, y, "Welder Calculations")
    y -= 4
    c.line(1 * inch, y, 5 * inch, y)
    y -= 14
    c.setFont("Helvetica", 9)
    c.drawString(1 * inch, y, f"Bend Deduction: {welder_calcs.get('bendDeductionMm', 0):.3f} mm")
    y -= 14
    c.drawString(1 * inch, y, f"Root Gap: {welder_calcs.get('rootGapMm', 0):.2f} mm  |  "
                               f"Landing: {welder_calcs.get('landingMm', 0):.2f} mm")
    y -= 14
    c.drawString(1 * inch, y, f"Weld Volume: {welder_calcs.get('weldVolumeCm3', 0):.4f} cm³  "
                               f"({welder_calcs.get('weldVolumeIn3', 0):.4f} in³)")

    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.drawCentredString(width / 2, 0.5 * inch, "Generated by WeldScan 3D — metalcut.pro")

    c.save()
    return buf.getvalue()


# ---------------------------------------------------------------------------
# DXF Export
# ---------------------------------------------------------------------------

def generate_dxf(
    segments: list[dict],
    ppi: float,
    title: str = "WeldScan 3D",
) -> str:
    """
    Generate a CNC-ready DXF file from contour segments.

    Each segment becomes a LINE entity in model space.
    Coordinates are converted from pixels to inches (the DXF drawing unit).

    Args:
        segments: list of {startPoint:{x,y}, endPoint:{x,y}} from edge_detection
        ppi:      pixels-per-inch calibration constant
        title:    document title (stored in DXF header)

    Returns:
        DXF file content as a string (UTF-8)
    """
    doc = ezdxf.new(dxfversion="R2010")
    doc.header["$INSUNITS"] = 1  # 1 = inches

    msp = doc.modelspace()

    for seg in segments:
        x1 = seg["startPoint"]["x"] / ppi
        y1 = -seg["startPoint"]["y"] / ppi   # invert Y (screen → CAD coords)
        x2 = seg["endPoint"]["x"] / ppi
        y2 = -seg["endPoint"]["y"] / ppi
        msp.add_line((x1, y1), (x2, y2))

    buf = io.StringIO()
    doc.write(buf)
    return buf.getvalue()
